# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_auto_20170107_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='revision',
        ),
    ]
