# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20170107_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uploader.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='revision',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
