# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_auto_20170107_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
