# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_auto_20170107_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
    ]
