# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 22:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0009_remove_uploadedfile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 7, 22, 7, 25, 864955)),
        ),
    ]
