# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 22:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0011_auto_20170107_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uploader.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 7, 22, 37, 15, 359875, tzinfo=utc)),
        ),
    ]
