# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 23:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('uploader', '0013_auto_20170107_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 7, 23, 6, 12, 328463, tzinfo=utc)),
        ),
    ]
