# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 03:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0014_auto_20170107_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='note',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 8, 3, 17, 6, 46856, tzinfo=utc)),
        ),
    ]
