# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 03:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0015_auto_20170108_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 8, 3, 54, 59, 657782, tzinfo=utc)),
        ),
    ]
