# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 04:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0016_auto_20170108_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 8, 4, 2, 32, 758989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='note',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
