# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import uploader.models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0017_auto_20170108_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=uploader.models.user_directory_path),
        ),
    ]
