# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0018_auto_20170118_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
