# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0019_auto_20170118_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
