# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0021_auto_20170118_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='name',
            new_name='display_name',
        ),
    ]
